runtime: python39

entrypoint: gunicorn -b :8081 main:app

handlers:
- url: /static
  static_dir: static  # Directorio donde se encuentran los archivos estáticos como CSS, JavaScript, imágenes, etc.

- url: /.*
  script: main.py  # Google App Engine utilizará un manejador web proporcionado automáticamente por tu aplicación

env_variables:
  ACCESS_TOKEN: EAAQqFleageABOx4JQ54XIehSjtSQQeXvDeqVf5ySAKA05USlzW9j243JgGSZAwRMXkZANbZCNZAXYPWj7cp7GZBI02Xkly8uv0XaE92jDE8MsUCRroHQrgAuZCfz4EYqRWdZBHxE3gcGXqNnNi3giZCyLf7968fdwXs9zAuHJy0uZB6LGYM1bCPQCSAhlTV8ZAWoD06xqhHsXZCQISqYraw

  APP_ID: 1172175354233312
  APP_SECRET: d2a5804385b57c5d2012c8cae65276cf
  
  VERSION: v19.0
  PHONE_NUMBER_ID: 274944972369887
  WHATSAPP_MARTIN: 59899639951
  WHATSAPP_FEDE: 59898808255

  VERIFY_TOKEN: 12345

  OPENAI_API_KEY: sk-proj-hDTeRrYC5Stt8sfjsPDUT3BlbkFJdU9bJW2yDRS8yDU2dpXc
  OPENAI_ASSISTANT_ID: asst_8hQUajLe9VSMwUSItmTUKSD9

  GS_CONFIG: pymes-422618-1bc91f408085.json
  
  GS_FILE: pymes
